id: I0E6AC9C4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T20:37:15+00:00'
last_modified: '2022-06-08T05:58:21.300513+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9994
  title: གསང་བདེ་འཇིགས་གསུམ་གྱི་བསྙེན་པའི་སྔོན་འགྲོའི་འདོན་ཆ་སོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    CB4F:
      image_group_id: I1KG9996
      title: ''
      total_pages: 554
      order: 1
      base_file: CB4F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
